### PR TITLE
Crosscheck rules between API and static rules

### PR DESCRIPTION
**Pull request by jchristgit**
See https://github.com/python-discord/site/issues/944

### CODE REVIEW

**Comment by jchristgit** [comment]
This is amazing. Absolutely stunning. Thank you so much. And please, don't make the coffee too hot, okay? I burnt myself the last time.

**Comment by jchristgit** [comment]
Oh, and no milk at all. I like it as pure as my editor. No milk at all. My coffee like my editor.

**Comment by jchristgit** [comment]
Seriously, man. As soon as I turn into president, the world will see these small QoL changes everywhere.

**Comment by jchristgit** [comment]
Lemon will be elected Head Of Technology. Or Head Of Public Relations. Maybe he can automate it.

**Comment by jchristgit** [comment]
Always be winning.

**Comment by ChrisLovering** [comment]
> Always be winning.

I agree

**Review by ChrisLovering — APPROVED** [review]

**Review by shtlrs — APPROVED** [review]
King !

**Pull request merged**
