### PR TITLE
command line instructions moved up

### LINKED ISSUE #509: Move command line instructions above PyCharm in guides
On various guides on the site such as the one on [Installing Project Dependencies](https://pythondiscord.com/pages/guides/pydis-guides/contributing/installing-project-dependencies/), you find the command line instructions at the very bottom of the page, below the (rather space consuming) guides for PyCharm.

On pages filled with images, it can be easy to miss the command line instructions for very important steps. Plus, it's likely that more people will use the command line instructions, since Python programmers use a large variety of editors/IDEs. I think it would be beneficial to move the command line instructions to the tops of these pages so that people will be able to find them easily.

Some pages that have this:
- https://pythondiscord.com/pages/guides/pydis-guides/contributing/cloning-repository/
- https://pythondiscord.com/pages/guides/pydis-guides/contributing/installing-project-dependencies/

### PR DESCRIPTION
**Pull request by soham4abc**
This PR fixes #509

### CODE REVIEW

**Review by whispersofthedawn — CHANGES_REQUESTED** [review]
I can't fully review at the moment, but could you reorder the "table of contents" at the top of both pages to match this new change?

**Comment by soham4abc** [comment]
> I can't fully review at the moment, but could you reorder the "table of contents" at the top of both pages to match this new change?

Done!!

**Review by kosayoda — APPROVED** [review]

**Comment by ToxicKidz** [comment]
Shouldn't this update [this page](https://pythondiscord.com/pages/guides/pydis-guides/contributing/installing-project-dependencies/) mentioned in the issue as well?

**Comment by kosayoda** [comment]
Does it not?

**Comment by ToxicKidz** [comment]
My mistake, it does

**Review by ToxicKidz — APPROVED** [review]

**Pull request merged**
