### PR TITLE
Add a field to track the time an infraction was last applied

### PR DESCRIPTION
**Pull request by ChrisLovering**
A default is set for backwards compatibility with bot version that don't explicitly give a value.

This is required to assist with https://github.com/python-discord/bot/issues/2130 and https://github.com/python-discord/bot/issues/2217 so that we can store when it was last edited. By comparing this date to the expiry date, we can get the absolute duration, rather than a rough duration which exhibits the issues above.

### CODE REVIEW

**Review by HassanAbouelela — APPROVED** [review]
Code looks valid

**Comment by ChrisLovering** [comment]
The migration has been tested against prod, it worked at took <1s locally.

**Comment by wookie184** [comment]
What is the purpose of this?

**Comment by ChrisLovering** [comment]
> What is the purpose of this?

Sorry, I left out a lot of context as we were discussing in #dev-contrib. I've updated the PR description with some of that context.

**Review by ionite34 — APPROVED** [review]
Added field appears correct for supporting new duration calculations, and does not affect current API.

**Pull request merged**
