### PR TITLE
Remove the admin app

### PR DESCRIPTION
**Pull request by jchristgit**
This app is completely unused. I assume it was planned to be a space for
customizing the Django admin, but we don't even have it in
`INSTALLED_APPS`, nor our URLs.

### CODE REVIEW

**Comment by sue-m-oh** [comment]
Is this the admin site that Scofflaw brought up the other day?

If so I believe you should also remove the mentions of it on the site [contributing guide](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/site/).

Nevermind!

**Comment by MarkKoz** [comment]
I guess this should be deleted too then https://github.com/python-discord/site/blob/main/pydis_site/apps/api/admin.py

**Comment by MarkKoz** [comment]
Oh, I think I misunderstood. You're just deleting the custom app, not disabling the entire Django admin feature.

**Comment by jchristgit** [comment]
> Oh, I think I misunderstood. You're just deleting the custom app, not disabling the entire Django admin feature.

Yes, this is dead code

**Review by MarkKoz — APPROVED** [review]
Kill confirmed.

**Review by D0rs4n — APPROVED** [review]

**Pull request merged**
