### PR TITLE
Improvements to Admin pages for the API Section

### PR DESCRIPTION
**Pull request by scragly**
I've added some QOL adjustments to the admin pages by defining `ModelAdmin` objects for ~~most~~ all of the API section's models:

## Bot Settings

<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :x: | :white_check_mark: |

### List View
Columns shown: name
Filter by: None

image

### Item View
Fields: name, data (editable)

image

</details>

## Documentation links
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

### List View
Columns shown: package, base url (editable), inventory url (editable)
Ordered by: package (alphabetical)
Searchable by: package
Filter by: None

image

### Item View
Fields: package, base url, inventory url

image
</details>

## Infractions
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | reason |

### List View
Columns shown: type, active, user, inserted, reason  
Ordered by: inserted descending
Searchable by: id, user name, user id, actor name, actor id, reason, type
Filter by: type, hidden, active, actor

image

### Item View
Fields: user, actor, type, hidden, active, inserted, expires, reason (editable)

image
</details>

## Log entries
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :x: | :x: |

### List View
Columns shown: timestamp, level, message
Searchable by: message
Filter by: log level, timestamp

Note: "application" has been removed from filter and columns as we no longer use this api for external logs.

image

### Item View
No changes.

image

</details>

## Deleted messages
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | :x: |

### List View
Columns shown: message id, author, channel id
Ordered by: id descending  
Searchable by: message id, content, author name, author id, actor name, actor id
Filter by: None

image

### Item View
Fields: id, author, channel id, content, embeds (pretty json formatting), context link, view log (link to staff.pydis log view)

image
</details>

## Message deletion contexts
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | :x: |

### List View
Columns shown: id, creation, actor
Ordered by: most recent  

image

### Item View
Fields: actor, creation, child messages (as inline tabular view)

image
</details>

## Nominations
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | reason<br>end reason |

### List View
Columns shown: username (with discrim.), active, reason, actor name (with discrim)
Ordered by: most recent  
Searchable by: user name, user id, actor name, actor id, reason, end reason  
Filter by: active, actor

image

### Item View
Fields: user, active, actor, reason (editable), created, ended, end reason (editable)

image
</details>

## Off topic channel names
<details>
<summary>See details</summary>

#### Permissions
<details>
<summary>See details</summary>

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

### List View
Columns shown: name
Searchable by: name
Filter by: used

image
</details>

### Item View
Fields: name, used

image
</details>

## Offensive messages
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | delete date |

### List View
Columns shown: message id, channel id, delete date
Searchable by: message id, channel id
Filter by: None

image

### Item View

Fields: message id (value hyperlinked to discord jumplink), channel id, delete date (editable) 

image
</details>

## Roles
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | :x: |

### List View
Columns shown: name (coloured)  
Ordered by: position  
Searchable by: name, id  
Filter by: None

image

### Item View

Fields:
 - id
 - name
 - colour
   - coloured text
   - shown as both hex & int values
 - permissions
   - value links to the Discord API Permissions Calc page to show all the permissions ([example](https://discordapi.com/permissions.html#104308297))
 - position

image
</details>

## API User
<details>
<summary>See details</summary>

#### Permissions

image

| View | Add | Delete | Change 
| :---:  | :---:  |  :---:  |  :---:  |
| :white_check_mark: | :x: | :white_check_mark: | :x: |

### List View
Columns shown: username (incl. discrim), top role (coloured), in guild  
Ordered by: username (incl. discrim)
Searchable by: name, id, role id  
Filter by: role membership, in guild

image

### Item View

Fields: username (incl. discrim), id, in_guild, role vertical list (coloured)

image
</details>

### CODE REVIEW

**Review by SebastiaanZ — COMMENTED** [review]
Is there a way to make certain fields optional in the Admin back-end? If you, say, edit a `note` infraction, you won't be able to save your changes unless you set an expiry date. 



I think that would be an improvement as well.

**Comment by fiskenslakt** [comment]
I'm in the middle of thoroughly testing this branch as I populate my local database, and I've run into an odd bug. Please tell me if you can reproduce it.

Steps to reproduce:
1. Go to `/admin/api/tag/f-strings/change/` on production site and copy the JSON content inside the embed field.
1. Go to `/admin/api/tag/` on your local development site and create a new tag with the `ADD TAG +` button
1. Enter a title for the tag
1. Paste in the copied JSON into the embed field
1. Click the `Save and continue editing` button

Expected behavior:
1. Tag is saved
2. Edit tag screen is displayed and tag markdown is rendered

What I got instead:
1. Tag is saved
2. Django raises a `KeyError: snake`

**Comment by lemonsaurus** [comment]
@scragly any idea when you'll be able to address the reviews here?

**Comment by scragly** [comment]
Tonight maybe. I only just got the local copy going again today.

**Comment by lemonsaurus** [comment]
excellent. thanks for the quick reply.

**Comment by lemonsaurus** [comment]
@scragly This pull request is very stale. It looks like it's like 98% done, so it'd be a shame to have to close it. I really wish you'd find some time to finish it, but otherwise I'm considering whether we should just merge it even with the reviews unaddressed. I mean, having this feature with a few bugs is probably better than never having it.

**Comment by scragly** [comment]
I should have a bit of time today to address the reviews and to bring the changes up to date with master. I'll try jump on after breakfast too get it sorted.

**Comment by scragly** [comment]
> If you, say, edit a `note` infraction, you won't be able to save your changes unless you set an expiry date.

The issue for non-expiring infractions being unable to save changes has been addressed coincidentally, but out of concern that the bot infraction tasks will desync if editing expiry is allowed external to the bot. 

I've double checked, and turning the expiry read-only results in successful reason edits.

**Comment by scragly** [comment]
> I'm in the middle of thoroughly testing this branch as I populate my local database, and I've run into an odd bug.

Through the power of laziness, neglect and sheer forgetfulness, much time has passed, and just as the water stream eventually erodes the rock, we have lost the presence of tags in the database, with them being stored back in repos. Hence, time is the true solution to all that is bad with the world.

**Comment by scragly** [comment]
I've gone through and tweaked edit permissions for certain models, and atm it's showing the following in the admin site:
image

Figured I'd give a bit of an update. I'll try get a proper update coming tomorrow, but unfortunately I'm absolutely wrecked and need sleep.

**Review by lemonsaurus — APPROVED** [review]
An exceptionally good PR. Beautifully described, well documented code, concise, and useful.

**Review by jb3 — APPROVED** [review]
Excellent PR

**Pull request merged**
