### PR TITLE
Add an API to post logs to.

### PR DESCRIPTION
**Pull request by jchristgit**
As promised. I ALWAYS DELIVER

However this is draft because I still want some suggestions on fields. Is this too much? Is it sufficient?

### CODE REVIEW

**Comment by MarkKoz** [comment]
Can you provide some context? What's the plan for using this API? So far I have gathered that the model has no field for the log's actual message and that the API only allows for creation, not retrieval.

**Comment by jchristgit** [comment]
Hello @MarkKoz thanks for the review for some reason I forgot that log lines tend to contain messages. The new commit accounts for this. The idea is that this will serve as our internal logging platform, this is the corresponding API to store logs. We will later build a UI in the web app to browse these, but we'll get there in steps.

**Review by MarkKoz — COMMENTED** [review]
Is the plan for messages to just post them as plain text? What about exceptions? It may be annoying to parse out the exceptions should we choose to do so.

**Comment by jchristgit** [comment]
Yes, messages will be plain text. Parsing out exceptions might be overthinking it a bit, we're not remaking Sentry after all

**Review by jerbob — APPROVED** [review]
Looks good to me.

**Pull request merged**
