### PR TITLE
removing margin-left property from base.css to fix the overflow 

### LINKED ISSUE #1015: Discord Button Shifts Off-Page at 1024-1040px Screen Width
Summary: When the screen width is between 1024 and 1040 pixels, the Discord button shifts to the right beyond the edge of the main page.

Environment: win10, screen resolution 1024x768, browser: Chrome 114 latest

Step to reproduse: 1. Open a web browser.
                               2. Enter the URL https://www.pythondiscord.com/ in the address bar.

Discord button 2

### PR DESCRIPTION
**Pull request by sarzz2**
## Summary
Fixes #1015 [Issue](https://github.com/python-discord/site/issues/1015)

## Description of changes
removing the margin-left property from base.css to fix the overflow caused by the discord button logo on the top right of the page when screen size is lowered.

### I confirm I have:
- [X] Joined the [Python Discord community](discord.gg/python)
- [X] Read the [Code of Conduct](https://www.pydis.com/pages/code-of-conduct) and agree to it
- [X] I have discussed implementing this feature on the relevant service (Discord, GitHub, etc.)

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]
Thank you!

**Review by kosayoda — CHANGES_REQUESTED** [review]
I tested the preview deployment, and unfortunately the issue is not fixed. The issue is still reproducible on:

- Stock chromium
image

- Firefox, with persistent scrollbars `General > Browsing > Always show scrollbars`:
image

Given how finnicky the issue is, I'm inclined to suggest the removal of both `padding-left` and `padding-right` directly, which fixes the issue in all my test cases. It is a visual change, but I don't think it hurts the look:

image
image

**Comment by sarzz2** [comment]
Removing both padding left and right makes the button look a little squeezed, we can just remove ```padding-right:2.5rem``` to fix the issue with persistent scrollbars on firefox.

Note: Chrome doesn't have this issue since the persistent scrollbar option is not available in settings afaik.

**Comment by kosayoda** [comment]
> ...we can just remove `padding-right:2.5rem` to fix the issue with persistent scrollbars on firefox.

Sounds good to me!

**Comment by sarzz2** [comment]
Merged the main branch and updated the file to remove padding.

**Comment by sarzz2** [comment]
@kosayoda could you review now and close PR if all is good?

**Review by kosayoda — APPROVED** [review]

**Pull request merged**
