### PR TITLE
Added Cloudflare to site sponsors

### LINKED ISSUE #514: Add Cloudflare to the Site Sponsors
Apparently they've been a sponsor for a long time, but are not listed. I'd love to add them, as an easy first PR.

### PR DESCRIPTION
**Pull request by Kronifer**
Closes #514 

Added cloudflare to the bottom of the site sponsors.

Image:

image

### CODE REVIEW

**Comment by Akarys42** [comment]
It looks quite big, can we make it smaller?

**Comment by Kronifer** [comment]
@Akarys42 thats the size they give me, do you want it resized?

**Comment by Kronifer** [comment]
@Akarys42 resized

**Review by Akarys42 — APPROVED** [review]
Lgtm, thanks a lot!

**Review by kosayoda — CHANGES_REQUESTED** [review]
image

The sponsor image no longer has a transparent background.

**Comment by Kronifer** [comment]
ill fix right away

**Comment by kosayoda** [comment]
@Kronifer I've assigned you the issue that this PR addresses, so you can continue work on it whenever. I'm going to close this PR for now as I don't think a sponsor image addition warrants this many changes/commits.

**Pull request closed without merging**
