### PR TITLE
Add Google's Python course to resources

### PR DESCRIPTION
**Pull request by AileenLumina**
Seems worth a mention to me. :)

### CODE REVIEW

**Comment by gdude2002** [comment]
This course enforces Google's Python style guide, rather than the much preferred PEP8. That could be problematic.

**Comment by lemonsaurus** [comment]
I am not sure I see this as a problem. The google style guide agrees with PEP8 on nearly everything. it's really meant more as a complimentary guide than a substitute

**Comment by justalemon** [comment]
As a side note, this course is for Python 2.6+ (from https://developers.google.com/edu/python/set-up#python-on-linux-mac-os-x-and-other-os):

```
Although Python 3.x is becoming more popular, this course is designed for Python 2.6 or later.
```

**Comment by lemonsaurus** [comment]
that, I am far more troubled by. I think that disqualifies it.

**Comment by AileenLumina** [comment]
As the one who originally brought this up, I agree, and I think this should be closed, but I'll let you decide. ^^

**Pull request closed without merging**
