### PR TITLE
feat: 'Edit on GitHub' for content articles

### LINKED ISSUE #459: Edit on GitHub for content articles.
At the top of an article in the `content` app, we should show an "Edit on GitHub" button.
The button when clicked should lead to the GitHub page for that file - something like https://github.com/python-discord/site/blob/main/docs/configuration.md

The button should have a nice logo, maybe an edit pencil or a github icon.
Here's one such mock implementation:
image

Improvements on the mock design can be to reduce the visual weight of the button, or finding a way to make it smaller yet accessible.

Anyone who wants to implement this can propose alternative implementations, feel free to do so in `#dev-contrib` or `#dev-dewikification`.

### PR DESCRIPTION
**Pull request by hedyhli**
## Description

Adds a link which allows users to view the page source on github for content articles.

Supersedes #623 and #506 
Closes #459 

- Shows up for all pages, including ones with sub-articles such as the popular [contributing page](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/)
- Does not show up in "folders" (ones without an actual page, such as [guides](https://www.pythondiscord.com/pages/guides/))
- Pencil icon used, similar to microsoft docs
- It's a simple link rather than a button because IMO, it is less attention-seeking and takes less visual space. (Viewers will probably not be using this link that often.) Plus, button implies an action, but this PR only adds a link to the page source (and not the actual online editor page on github) hence an action is not taken, making a link more suitable

## Screenshots

**A page with sub-articles (aka category page?) [`/pages/guides/pydis-guides/contributing/`](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/)**
pydis-editgh-1

**A page without sub-articles: [`/pages/guides/python-guides/discordpy_help_command/`](https://www.pythondiscord.com/pages/guides/python-guides/discordpy_help_command/)**
pydis-editgh-2

## Implementation

- Using a configuration in settings.py for github url, so it's not hardcoded
- Using a template filter to get the url given the request path
- The link is added on the right of the breadcrumb at the very end. I didn't feel like it makes sense to put it before the sub-articles dropdown, if any.
- The link together with the sub-articles dropdown is in a right-justified flex container, so the pull-right on sub-articles dropdown is no longer needed... I think

Note, github does have an _edit_ link that links the user to an online editor. This was not used for serveral reasons:
1. Other docs such as VS Code doesn't do this
2. It creates a fork for the user (AFAIK) which the user may not want
3. The user can chose where to go next when linked to the source page only (and not the edit link) - download, view raw, or edit.

## Design

Feedback appreciated on
- whether the pencil icon is more suitable than the github logo (as in original mock implementation in the issue by lemon)
- link rather than a button
- placing of the link in terms of semantics: should it be on the same line as the title instead? However, this will take up space for the title line for small screens, making the title wrap
- whether it's a good idea (or conventional?) to put the github source url as a variable in settings.py

### Support for smaller screens

Makes a mess when the screen is small (not able to fit the breadcrumb and the Edit on GitHub link in one line), making the link segmented.

I noticed that this issue is also present currently (unrelated to this PR) for the sub-articles dropdown: if the screen is small, the dropdown makes the title overflow, squeezing itself into the same line as the title. Perhaps this would need to have a separate issue opened to have the items on the right of the breadcrumb (sub-articles dropdown + Edit on GitHub) be wrapped on a new line, each taking a another screen width, so that the page is more accessible.

## Todo

- [x] Test for more pages
- [x] Fix icon
- [ ] Maybe add tests for the template filter
- [x] Maybe not hardcoded GitHub prefix URL?

### CODE REVIEW

**Comment by Xithrius** [comment]
@hedyhli Greetings. What's the status of this PR? Thanks!

**Comment by hedyhli** [comment]
Hi Xithrius! Unfortunately I've been pretty busy with school lately. I'd love to continue working on it though but I can't guarantee when I'll have time for it, hopefully before the end of April by the latest.

**Comment by Xithrius** [comment]
@hedyhli Greetings. What is your status on this PR?

Thanks!

**Comment by hedyhli** [comment]
Finally found some free time which fingers crossed might last until as much as the end of the year! So I'll be working on this for the coming weeks. Actually I have already resumed on this, but I have to set up my dev environment all over again and had some problems with docker the last time I tried (honestly I can't even remember if I used the docker setup last year).

**Comment by hedyhli** [comment]
Marking this as ready for review, feedback welcome!

**Comment by Xithrius** [comment]
Very good.

**Review by wookie184 — COMMENTED** [review]
Looking at the build preview it seems it gets a bit squished up on mobile 
image

Other than that this seems great though. Any thoughts on how the behaviour on mobile could be improved?

**Comment by hedyhli** [comment]
> Any thoughts on how the behaviour on mobile could be improved?

It should wrap so the whole thing is to the next line, like I mentioned in the description. Either same line as sub-articles or each one their own line.

At the moment sub-articles seems to be wrapping to fit on the same line as the title. I doubt this works when title is longer (for pages other than the contributing index page) even before adding the edit on github like, so it would probably be best to have them both take their own line before the title.

I’ll experiment with what can be done, thanks!

**Comment by jchristgit** [comment]
Hi @hedyhli, were you able to find some possible fix for mobile? If it's too much of a hassle I believe we should also just be able to skip adding the edit button on mobile outright, as it's probably much less used than on desktop.

**Comment by jchristgit** [comment]
I have opened a PR at https://github.com/python-discord/site/pull/626 that has your commits to allow maintainer edits to get the final changes in to merge it.

**Comment by hedyhli** [comment]
Sad I didn’t get time to work on this, but thanks a lot for continuing on my progress!

**Comment by jchristgit** [comment]
Thanks for laying the foundation with your work! I am looking forward to having this on the live site.

**Pull request closed without merging**
