### PR TITLE
Vagrant development

### PR DESCRIPTION
**Pull request by Inveracity**
this branch adds a vagrant file and a bootstrap script to get a development environment up and running automatically with vagrant and virtualbox

### CODE REVIEW

**Comment by gdude2002** [comment]
I'm not the right person to review this, I'm not gonna be using Vagrant at all because my network is far too slow at the moment. I don't have a way to test this PR without spending hours on it.

**Review by jb3 — APPROVED** [review]
Tested on Arch Linux 4.15, no issues.

**Comment by jb3** [comment]
Regarding the vagrant setup, is the 2048mb memory required? I see that in the Vagrantfile it sets the VM to that but I'd say that 512mb is probably fine.

**Comment by Inveracity** [comment]
I just tested this, and I concur.
PR: https://github.com/discord-python/site/pull/28

**Pull request merged**
