### PR TITLE
Correcting/adding Udemy tooltip in resources as per Issue #137

### PR DESCRIPTION
**Pull request by SebastiaanZ**
As issue #137 specified, the tooltip for the Udemy course "Automate the Boring Stuff with Python" was wrong, as it suggested you could follow the full course for free. I've corrected it to say it's a paid course, but has a couple of free sample videos.

I've also used the same tooltip for the other Udemy course on resources.

### CODE REVIEW

**Review by sco1 — COMMENTED** [review]
https://github.com/python-discord/site/blob/7d51f286840226da9dd78b6fd8c0a8e250004788/static/resources.json#L363

Is this coupon code perpetually valid?

**Comment by SebastiaanZ** [comment]
I don't know, @sco1. I didn't add it, but it's still valid and has been in our resources list for a while now. 

@heavysaturn added it on Apr 27, 2018 in #59

**Comment by sco1** [comment]
Seems like it's pulled directly from their site

**Review by sco1 — APPROVED** [review]

**Review by tagptroll1 — APPROVED** [review]
Easy fix

**Pull request merged**
