### PR TITLE
Fix typos across codebase

### PR DESCRIPTION
**Pull request by hedyhli**
## Changes
-  `./pydis_site/apps/resources/resources/tools/ides/thonny.yaml:1`: specifically
- `./pydis_site/apps/content/resources/guides/pydis-guides/helping-others.md:115`: considered
- `./pydis_site/apps/content/resources/guides/pydis-guides/contributing/issues.md`:59 labels
- `./pydis_site/apps/content/resources/guides/pydis-guides/contributing/sir-lancebot.md:99`: recommend
- `./pydis_site/apps/content/resources/guides/pydis-guides/contributing/site.md:111`: particularly
- `./pydis_site/apps/content/resources/guides/pydis-guides/contributing/sir-lancebot/env-var-reference.md:29`: Integer
- `./pydis_site/apps/content/resources/guides/pydis-guides/contributing/sir-lancebot/env-var-reference.md:67`: calculating
- `./pydis_site/apps/api/tests/test_off_topic_channel_names.py:157`: response

## Notes
- I didn't touch the code jam and game jam typos because I'm think they should probably be preserved as is since it's a historical thing.
- There were a few 'seperated' typos which I didn't change because I *think* it's just another way of spelling it?
- In the offensive words test there was a keyword argument named `fied` which I didn't touch because I wasn't sure where that was from.

### CODE REVIEW

**Comment by ChrisLovering** [comment]
Thanks for this, you are correct https://github.com/python-discord/site/blob/main/pydis_site/apps/api/tests/test_offensive_message.py#L61 should be `field=field`. Would you be able to add this to the PR too? :)

**Comment by wookie184** [comment]
> There were a few 'seperated' typos which I didn't change because I think it's just another way of spelling it?

I'm fairly sure separated is the only correct spelling, and google seems to agree (although now that i've stared at both spellings for a bit of course they both look weird 😄 )

**Comment by hedyhli** [comment]
> I'm fairly sure separated is the only correct spelling, and google seems to agree (although now that i've stared at both spellings for a bit of course they both look weird 😄 )

Haha 'label' looked soo like 'lah-belle' for me yesterday.

I use seperated if I don't have spellcheck on because in american accent the 'per' has more curl to it than e.g. in australian accent... generally.

Guess I'll fix those 'seperated's then.

**Comment by hedyhli** [comment]
> Thanks for this, you are correct https://github.com/python-discord/site/blob/main/pydis_site/apps/api/tests/test_offensive_message.py#L61 should be `field=field`. Would you be able to add this to the PR too? :)

Done! I also fixed two `succinct` typos. Didn't think of googling it before the idea from wookie, stupid me.

**Review by ChrisLovering — APPROVED** [review]

**Review by Akarys42 — APPROVED** [review]

**Pull request merged**
