### PR TITLE
URLs: add an allow everything robots.txt

### PR DESCRIPTION
**Pull request by Akarys42**
This commit simply adds a `robots.txt` file from within the URL configuration.

### CODE REVIEW

**Review by Kronifer — APPROVED** [review]
Looks good!

**Review by jb3 — CHANGES_REQUESTED** [review]
I'd rather have the robots.txt content in a multi-line string than with \n, also we shouldn't allow everything, we should disallow /admin/.

**Comment by Kronifer** [comment]
Oop that probably makes sense

**Comment by jchristgit** [comment]
> I'd rather have the robots.txt content in a multi-line string than with \n, also we shouldn't allow everything, we should disallow /admin/.

What's the value in disallowing `/admin/` though?

**Comment by jchristgit** [comment]
@Akarys42 can you address the merge conflict and Joe's comment? It's good to me otherwise.

**Review by jchristgit — APPROVED** [review]
Thanks!

**Comment by Akarys42** [comment]
We will be using a worker for this

**Pull request closed without merging**
