### PR TITLE
Added Favicon

### PR DESCRIPTION
**Pull request by NeilShah2026**
Added the Py-Dis Logo As A Favicon For The 404 Page

### CODE REVIEW

**Review by HassanAbouelela — CHANGES_REQUESTED** [review]
Hmm, let's stop using Imgur on our site. Can you use the asset from the github repo, or add it to the static files?

**Comment by NeilShah2026** [comment]
Ok

**Review by jb3 — CHANGES_REQUESTED** [review]
Can we include the support for `/favicon.ico` in this PR as well? Or if not, open an issue to do so.

That means that devices would fallback on pages where we don't explicitly specify a favicon.

**Comment by ChrisLovering** [comment]
It seems the fork this PR is based from has been deleted, so changes cannot be made. Therefore, I am closing this PR.

If someone still wants to implement these changes, please open an issue for it to be discussed first.

**Pull request closed without merging**
