### PR TITLE
Changes -am to -m

### PR DESCRIPTION
**Pull request by robertt**
Pretty sure this is an error, and it should be `git commit -m`, not `git commit -am`

### CODE REVIEW

**Comment by gdude2002** [comment]
Why do you think this is an error?

**Comment by jb3** [comment]
No, that's intentional. The `-a` flag adds all unstaged files, note how we don't say anything about `git add` in that. If you see this as an error then feel free to bring it up but this is not a typo or error.

**Comment by robertt** [comment]
Yes but its more readable, also maybe do `git commit -a -m "Message"`, then you can explain what -a does.

**Comment by gdude2002** [comment]
This wasn't supposed to be a definitive guide. @JoeBanks13 is incorrect in that we do talk about adding files directly, but I included `a` because the guide is for absolute beginners to contribute to their code jam projects - not for actually learning Git.

**Comment by robertt** [comment]
Understandable

**Pull request closed without merging**
