### PR TITLE
pipenv and dockerfile

### PR DESCRIPTION
**Pull request by Inveracity**

### CODE REVIEW

**Comment by gdude2002** [comment]
Tox needs updating to ignore the venv

**Comment by greysteil** [comment]
Would you be up for using [Dependabot](https://dependabot.com) to keep the dependencies in the Pipfile / Pipfile.lock up-to-date? I built it, and it's totally free for open source - I'm just trying to get more people using it so I can get its Pipenv support perfect. :octocat:

**Comment by greysteil** [comment]
Woah, you guys are one step ahead of me and Dependabot is already running on this repo. ❤️ and sorry for the spam!

**Comment by lemonsaurus** [comment]
That's alright, thanks for making Dependabot. For the most part it's a great tool, although the recent Flask 1.0 PR short changed us a bit. :stuck_out_tongue:

**Comment by greysteil** [comment]
👍, well please feel free to ping me whenever there's anything it could have done better.

**Comment by gdude2002** [comment]
Oh hey, it's awesome to see someone involved with Dependabot on here.

I used to use Gemnasium on an older GH org, and it's just.. It tells you about the update, but doesn't PR, doesn't give more than version numbers.. Dependabot is a _huge_ improvement over that.

The issue @1mn is referring to is just that there were some API changes in Flask 1.0 that broke our build. I wouldn't expect an automated PR process to be able to deal with that.

**Comment by greysteil** [comment]
👍. One day I'd like Dependabot to be able to apply patches provided by library maintainers to automatically handle breaking changes. That day is probably a long way away, though!

**Comment by gdude2002** [comment]
@greysteil Do you have any plans to support GitLab?

I'm sure you can imagine that that'll be an important target moving forward :P

**Comment by greysteil** [comment]
Yes - we've had quite a few people ask for it over the last few months, and if we start seeing lots of organisations move then it'll rapidly become a priority. It's about a week's worth of work on my side, so something we can add relatively rapidly when the time comes.

**Comment by gdude2002** [comment]
You can add us to that list of organisations. :>

GitLab saw around 300k projects migrated from GitHub yesterday, so it might be worth looking at.

**Pull request merged**
