### PR TITLE
Edit on GitHub feature for content

### LINKED ISSUE #459: Edit on GitHub for content articles.
At the top of an article in the `content` app, we should show an "Edit on GitHub" button.
The button when clicked should lead to the GitHub page for that file - something like https://github.com/python-discord/site/blob/main/docs/configuration.md

The button should have a nice logo, maybe an edit pencil or a github icon.
Here's one such mock implementation:
image

Improvements on the mock design can be to reduce the visual weight of the button, or finding a way to make it smaller yet accessible.

Anyone who wants to implement this can propose alternative implementations, feel free to do so in `#dev-contrib` or `#dev-dewikification`.

### PR DESCRIPTION
**Pull request by jchristgit**
Pulled from https://github.com/python-discord/site/pull/626 to allow maintainer edits

Hidden in mobile:

image

Closes #459.

### CODE REVIEW

**Review by ChrisLovering — APPROVED** [review]

**Comment by wookie184** [comment]
Comparing https://deploy-preview-949--pydis-static.netlify.app/pages/guides/pydis-guides/contributing/sir-lancebot/ to https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/ it seems like this causes the rest of the page to drop down a bit.

Before:
image

After:
image

Any ideas on why this is?

**Comment by jchristgit** [comment]
@wookie184 yes I have seen that, but I have no idea what causes it. Inspecting the layout in Firefox I concluded that it's no margin or padding from the element itself. I also concluded that it's probably not noticeable by anybody and was hoping I could sweep it under the rug. Unfortunately, you have crossed through my plan to do it.

Any other idea where we can check what's causing the surplus whitespace apart from the layout box in devtools? I also tried to use a `span` instead of `div` to no success.

**Comment by ChrisLovering** [comment]
@jchristgit See @hedyhli's messages here for some solutions
https://canary.discord.com/channels/267624335836053506/635950537262759947/1100602004188958740

**Comment by jchristgit** [comment]
I saw these but I don't really have the CSS-fu to drive it to the finish line with the vertical stacking :(

**Comment by hedyhli** [comment]
Hey there, so I've played around with the HTML a little and it seems this patch works:
https://paste.pythondiscord.com/raw/fexodipane

Basically comparing the elements from before this PR and after, the container appears to gained a height, and the breadcrumb `<section>` also changed because of the added flex div element. So I decided to take it out of the container, then modify the CSS classes a little.

Hopefully this diff isn't a 'hacky' fix though (otherwise it might pose problems in the future).

*Note: If you compare the positioning of sub-articles and edit-on-gh before and after applying the patch, you might notice the two having moved towards the right a little, it could possibly be fixed with something like a `margin-right`. IMO it's more trivial than the entire content dropping down as wookie pointed out.*

**Review by wookie184 — APPROVED** [review]
Looks good, thanks @hedyhli for the help with this!

**Pull request merged**
