### PR TITLE
Udacity Python course

### PR DESCRIPTION
**Pull request by ahmedalbayati**
I've added the "Programming Foundations with Python" course from Udacity.

### CODE REVIEW

**Comment by gdude2002** [comment]
These items are supposed to be in alphabetical order - please do that.

**Comment by gdude2002** [comment]
It may also be worth mentioning that this course does expect a foundational Python experience - for example, conditionals, loops and functions - and assumes that you already know them.

**Comment by gdude2002** [comment]
Additionally, you should read the reviews over [here](https://www.class-central.com/course/udacity-programming-foundations-with-python-2013#reviews) and consider those in your submission.

Do you feel that this course is appropriate for absolute beginners?

**Comment by ahmedalbayati** [comment]
Okay, so I alphabetically ordered the course.

**Comment by ahmedalbayati** [comment]
I think the course is appropriate cause it teaches OOP in a very good way. Many beginners have a hard time  differentiating classes from functions. However I think you're still right, cause it doesn't teach much about loops and other necessary stuff. Could making a "beginner - intermediate - advanced" section be a good idea?

**Comment by ahmedalbayati** [comment]
What do you think about [this course](https://eu.udacity.com/course/introduction-to-python--ud1110)?

**Comment by ahmedalbayati** [comment]
That one could be good for the "beginner section" and then we'll put the other one in the "intermediate section".

**Comment by schwartzadev** [comment]
@ahmedalbayati I submitted a PR to your branch to remove the European prefix on the Udacity URL. I would be weary of adding courses that you just find online - you might want to either take the course or spend a while reading the reviews to make sure its quality. Cheers!

**Comment by ahmedalbayati** [comment]
This is not a random course. I took the course while learning Python and really enjoyed it, though it could be considered slightly "intermediate" that's why we should make sections for each level.

**Comment by gdude2002** [comment]
I don't think making sections at this early stage where we have like.. maybe 10 resources is worth doing. We'd just clutter up the page; it'd look awful.

I haven't had time to really look into the course as we're preparing for the code jam at the moment.

**Comment by gdude2002** [comment]
I'm going to close this for now. I don't feel that this recommendation had enough research into it, and I'm specifically cautious because Udacity courses can be created by literally anyone.

**Pull request closed without merging**
