### PR TITLE
Add LT and GT to supported otn chars

### PR DESCRIPTION
**Pull request by ChrisLovering**
Does what it says on the tin.

### CODE REVIEW

**Review by D0rs4n — APPROVED** [review]

**Review by onerandomusername — COMMENTED** [review]
Are these the best unicode characters for this?

\u276e and \u276f might be better looking substitutes.

**Review by onerandomusername — APPROVED** [review]
Looked at what they all look like on discord, these are the best characters for this purpose.

**Comment by onerandomusername** [comment]
What were all of the force pushes for? I don't see any difference since the last time I reviewed it.

**Comment by ChrisLovering** [comment]
> What were all of the force pushes for? I don't see any difference since the last time I reviewed it.

renamed the migration file, since it had it's auto generated name

**Comment by onerandomusername** [comment]
gotcha

**Review by onerandomusername — APPROVED** [review]

**Review by Akarys42 — APPROVED** [review]

**Pull request merged**
