### PR TITLE
Feature/darktheme

### PR DESCRIPTION
**Pull request by GDWR**

### CODE REVIEW

**Comment by GDWR** [comment]
Currently waiting on https://github.com/lemonsaurus/django-simple-bulma/issues/86

**Comment by Xithrius** [comment]
@GDWR fix conflicts.

Thanks.

**Comment by jchristgit** [comment]
Hello

It has come to my attention that Python Discord . Com still has no Dark Theme switch. I was saddened by this and, head hanging down, trotted to this pull request to express my feelings of sadness.

django-simple-bulma recently had my PR merged that added a flag to skip adding JS, which I _think_ should help with implementing this. What do you think?

**Comment by jchristgit** [comment]
Hi @GDWR. Do you still have time to work on this pull request or would you prefer if somebody else could pick it up?

**Comment by GDWR** [comment]
I'd prefer it if somebody could pick this up, this branch is now 2 years behind so would suggest using it as a reference. although rebasing should be relatively easy.

**Comment by GDWR** [comment]
View #1176 as successor

**Pull request closed without merging**
