### PR TITLE
adds beginnings of docs

### PR DESCRIPTION
**Pull request by Inveracity**

### CODE REVIEW

**Comment by Zwork101** [comment]
This seems overly complicated, I see no reason to run it in a VM. In addition, the docs don't including setting up the database, and creating the environment variables.

**Comment by Inveracity** [comment]
@Zwork101 it is entirely optional, there is no hard requirement to run this in a VM. Good points though, I've included notes on these things now.

**Comment by gdude2002** [comment]
Would we not use [the wiki](https://github.com/discord-python/site/wiki) for this?

**Comment by Inveracity** [comment]
@gdude2002 good point, didn't think about that

**Comment by Inveracity** [comment]
Moved to wiki

**Pull request closed without merging**
