### PR TITLE
Use proper logos and better positioning in the footers

### LINKED ISSUE #458: Django logo is not aligned with baseline of text in the footer
bild

Here is a close up

bild

bild

The Bulma logo is also a bit off, but it's close enough to not be visible at small sizes I think (I couldn't even notice until I zoomed in to take the screenshots above).

### LINKED ISSUE #662: Improve logos on the landing page.
Right now, there are three problems with the logos displayed in our sponsor hero and in the footer of the site.

## An alignment issue with the logos on Windows.
This problem is described in #458. We should optimize the `background-position` so that these logos will be optimally aligned on Windows machines, since our typical visitor is a Windows user.

## Hacky filtering to turn logos into white logos
Right now, we're using `filter` in CSS to turn the Django and Linode logos into something that will fit on our footer. This causes a weird display problem on mobile (seen in #458), and also poses a problem for implementing the dark theme. Let's just add staticfiles for these logos in the right size, and we will reduce the load time and make it much easier to build a dark theme around.

## Sponsor logos are arbitrarily sized
Why is the CloudFlare logo absolutely _enormous_, but other logos (like netCup) are _tiny_? It certainly doesn't represent the scope of the partnerships we have with these companies. Let's try to make these sizes more even, or choose different logos that can better fit into a smaller space for some partners.

I'll be tackling this personally.

### PR DESCRIPTION
**Pull request by hedyhli**
Closes #662, and as part of it, also closes #458.

Relevant `#dev-contrib` discussion: https://discord.com/channels/267624335836053506/635950537262759947/1220627130644434996

### Changes

Footer logos and positioning:
- Switch from CSS filtering to actual logos with white text.
- Adjust positioning to align all text in the logos with baseline and ensure they're center aligned with a uniform side spacing.

### CODE REVIEW

**Review by wookie184 — COMMENTED** [review]
The text alignment still isn't perfect for me (firefox on windows), is it the same for you?
Before:
image
After:
image

The other changes seem good though.

**Comment by hedyhli** [comment]
It should be alright in both windows and android now.

On iOS, it's pretty misaligned vertically if I zoom in, but it's probably somewhat subtle otherwise.

Since this isn't such a major issue (I've made sure no part of the image is cut off on all platforms) we'll just make sure it looks good for the majority of our users for now, as lemon suggested in the linked discussion. Considering that this is web dev, I wonder if a cross-platform solution even exists.

[Descenders](https://en.wikipedia.org/wiki/Descender) in Django and Netcup which is what caused the issue can't really be fixed without hardcoding the vertical offsets, but I've cropped the linode icon and switched to the text-only Bulma logo (both of which has no descenders) so it will show up aligned on all platforms.

**Review by wookie184 — APPROVED** [review]
It looks really good for me now
image

I agree with that it's not massively important so whatever balance you think seems best between different platforms is good with me.

**Comment by hedyhli** [comment]
Of course, wookie, I hacked into your computer to test it! ;P

But yes, since they're fairly small logos in the footer I don't think the offsets on iOS are _that_ noticeable. We could see if anyone complains.

**Review by jchristgit — APPROVED** [review]
Thanks!

**Pull request merged**
