### PR TITLE
Linode branding

### PR DESCRIPTION
**Pull request by lemonsaurus**
Added the following to the footer:
image

And added this to the code jams page:
image

### CODE REVIEW

**Review by SebastiaanZ — DISMISSED** [review]
Looks good enough for me!

**Review by jerbob — APPROVED** [review]
Looks good to me!

**Review by SebastiaanZ — APPROVED** [review]
This looks better! And I've taken a longer look at the commit!

**Comment by lemonsaurus** [comment]
thanks guys.

**Pull request merged**
