### PR TITLE
Off-topic names using tracking (v2)

### PR DESCRIPTION
**Pull request by ks129**
See #348 for more information. This PR got reverted because of mess with migrations. Fixed it here.

### CODE REVIEW

**Review by lemonsaurus — APPROVED** [review]
Looks good to me.

**Review by Akarys42 — APPROVED** [review]
Looks good to me

**Review by SebastiaanZ — DISMISSED** [review]
Tested; works now.

**Review by SebastiaanZ — APPROVED** [review]
Tested after update from master as well.

**Pull request merged**
