### PR TITLE
fix: use new domain for bot tutorial resource

### PR DESCRIPTION
**Pull request by vcokltfre**
Simple as the title says really; this is the domain the tutorial lives at now.

### CODE REVIEW

**Comment by wookie184** [comment]
Thanks, it looks like there are a couple of other occurences of the old domain (https://github.com/search?q=repo%3Apython-discord%2Fsite%20vcokltfre.dev&type=code), could you update them too?

**Review by shenanigansd — APPROVED** [review]
:shipit:

**Comment by vcokltfre** [comment]
> Thanks, it looks like there are a couple of other occurences of the old domain (https://github.com/search?q=repo%3Apython-discord%2Fsite%20vcokltfre.dev&type=code), could you update them too?

:ok_hand: all done

**Review by wookie184 — APPROVED** [review]
Great, thanks!

**Pull request merged**
