### PR TITLE
Added SVG file and edited navbar accordingly

### PR DESCRIPTION
**Pull request by jerbob**
I've made an Optimized SVG file for the site.
This PR adds the SVG to the Navbar, replacing the PNG banner.

### CODE REVIEW

**Comment by lemonsaurus** [comment]
this kind of a PR would be really nice if it had some pictures.

**Comment by jerbob** [comment]
**Previous homepage:**
image
**Current homepage:**
image

**Comment by jerbob** [comment]
**SVG image:**

**Comment by lemonsaurus** [comment]
MAKIN LOVE
MAKIN LOVE FOR TWO
MAKIN LOVE FOR TWO MINUTES

**Review by lemonsaurus — APPROVED** [review]

**Pull request merged**
