### PR TITLE
Fix broken links and remove extraneous space in timeline

### PR DESCRIPTION
**Pull request by ichard26**
Many thanks to @Rainb0wCodes for making me aware of the broken links.

This is not embarrassing in any way, not at all...

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]

**Comment by jchristgit** [comment]
@shtlrs Good morning

Do you know why `git` fails in the fixup blocker CI?

```

Run commit_messages=$(git log origin/main..fork/update-timeline-rev-2 --format="%h %B" --grep "^fixup" --oneline)
  commit_messages=$(git log origin/main..fork/update-timeline-rev-2 --format="%h %B" --grep "^fixup" --oneline)
  if [ -n "commit_messages" ]; then
      echo -e "$RED Error: Make sure that all 'fixup' prefixed commits are squashed before merging."
      echo -e "$RED Commits that need fixing:"
      while IFS= read -r line; do
        echo -e "$YELLOW${line}"
      done <<< "$commit_messages"
      exit 1
      exit 1
  fi
  shell: /usr/bin/bash -e {0}
  env:
    RED: \033[0;31m
    YELLOW: \033[0;33m
fatal: ambiguous argument 'origin/main..fork/update-timeline-rev-2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: Process completed with exit code 128.
```

**Comment by shtlrs** [comment]
Good morning sir.

Yes, it's because i forgot to make a new workflow that needs to run on the pull_request_target event.

Also, another pr needs to be Merged for it to be fully
 functionalhttps://github.com/python-discord/.github/pull/24

So, we can either bypass this, or remove the usage of it then rebase this branch.

Sorry for the hurdle.

**Comment by jchristgit** [comment]
> Sorry for the hurdle.

Wo gehobelt wird, da fallen Späne!!!!!!!!!!

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
